# Generated by Django 4.2.2 on 2023-07-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('photo', models.ImageField(upload_to='image')),
                ('color', models.CharField(max_length=1)),
                ('size', models.CharField(max_length=1)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
