# Generated by Django 4.2.2 on 2023-07-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovi', '0002_alter_product_options_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
